# 待编码文件路径
text = ["text.txt"]

# 键对开销表路径
costs = "cfg/cost-map.tsv"

# 词库路径
dict = "rime.dict.yaml"

# 键盘布局：各手指和各排的键值
# 注释掉则不分析使用率
layout = [
    "1qaz", # 左小指
    "2wsx", # 左无名指
    "3edc", # 左中指
    "4rfv5tgb", # 左食指
    "6yhn7ujm", # 右食指
    "8ik,", # 右中指
    "9ol.", # 右无名指
    "0p;/-['=]", # 右小指
    " ", # 拇指
    "1234567890-=", # 数字排
    "qwertyuiop[]", # 上排
    "asdfghjkl;'", # 中排
    "zxcvbnm,./", # 下排
    " " # 空格排
]
